import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {Footer} from "@/containers/Footer/Footer";
import AuthProvider from "@/components/AuthProvider";
import "./globals.css";
import React from "react";
import {NavBar} from "@/components/NavBar/NavBar";
import {cn} from "@/lib/utils";
import {HeroImage} from "@/components/HeroImage/HeroImage";

import styles from './layout.module.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <AuthProvider>
          <html lang="en">
              <body className={cn(inter.className, styles.body)}>
                <HeroImage title='Recipes' subtitle={'Engoy your meal!'}>
                    <NavBar className={'nav'}/>
                </HeroImage>
                  <main className={cn(styles.main, 'my-4 md:my-8')}>
                      {children}
                  </main>
                <Footer className={styles.footer}/>
              </body>
          </html>
      </AuthProvider>
  );
}