import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Navigation} from "@/components/navigation";
import {Footer} from "@/containers/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Navigation />
          <main className='min-h-screen flex flex-col'>
              {children}
          </main>
        <Footer />
      </body>
    </html>
  );
}
